"""
Database Generator Module

This module provides functionality to generate synthetic database content
based on schemas for information-theoretic experiments.
"""

import numpy as np
import logging
from typing import Dict, List

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


class DatabaseGenerator:
    """Generate synthetic database content based on schemas."""

    def __init__(self, seed: int = 42):
        """
        Initialize the database generator.

        Args:
            seed: Random seed for reproducibility
        """
        self.rng = np.random.RandomState(seed)

    def generate_database(self, schema: Dict, num_rows_per_table: int = 1000) -> Dict:
        """
        Generate synthetic database content based on schema.

        Args:
            schema: Database schema as generated by SchemaGenerator
            num_rows_per_table: Number of rows to generate per table

        Returns:
            Dictionary containing tables with their data
        """
        database = {
            "metadata": schema["metadata"],
            "tables": {}
        }

        # Process tables in order (to handle foreign key references)
        for table_name, table_schema in schema["tables"].items():
            table_data = []

            # Generate data for each row
            for row_id in range(num_rows_per_table):
                row = {"id": row_id}

                # Generate data for each column
                for col_name, col_schema in table_schema["columns"].items():
                    # Skip id column (already set)
                    if col_name == "id":
                        continue

                    # Handle foreign keys
                    if "foreign_key" in col_schema:
                        ref_table = col_schema["foreign_key"]["references"]
                        # Randomly select an ID from the referenced table
                        if ref_table in database["tables"]:
                            ref_data = database["tables"][ref_table]
                            row[col_name] = self.rng.choice(ref_data)["id"]
                        else:
                            # Reference to a table not yet created, use placeholder
                            row[col_name] = self.rng.randint(0, num_rows_per_table)
                    else:
                        # Generate data based on column type
                        data_type = col_schema["type"]
                        if data_type == "integer":
                            row[col_name] = self.rng.randint(0, 1000)
                        elif data_type == "float":
                            row[col_name] = self.rng.random() * 100
                        elif data_type == "string":
                            # Generate a random string
                            length = self.rng.randint(5, 20)
                            chars = [chr(self.rng.randint(97, 122)) for _ in range(length)]
                            row[col_name] = "".join(chars)
                        elif data_type == "date":
                            # Generate a random date in ISO format
                            year = self.rng.randint(2000, 2023)
                            month = self.rng.randint(1, 13)
                            day = self.rng.randint(1, 29)  # Simplified
                            row[col_name] = f"{year}-{month:02d}-{day:02d}"
                        elif data_type == "boolean":
                            row[col_name] = bool(self.rng.randint(0, 2))

                table_data.append(row)

            database["tables"][table_name] = table_data
            logger.info(f"Generated {len(table_data)} rows for table '{table_name}'")

        return database


if __name__ == "__main__":
    # Example usage (requires schema_generator.py)
    from schema_generator import SchemaGenerator

    # Generate a schema
    schema_gen = SchemaGenerator(seed=42)
    schema = schema_gen.generate_schema(entropy_bits=5.0)

    # Generate database content
    db_gen = DatabaseGenerator(seed=42)
    database = db_gen.generate_database(schema, num_rows_per_table=100)

    # Print some statistics
    for table_name, table_data in database["tables"].items():
        print(f"\nTable: {table_name}")
        print(f"Rows: {len(table_data)}")
        if table_data:
            print(f"Sample row: {table_data[0]}")